version: '3.9'

services:
  meloflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "DATABASE_URL=host=150.95.82.125 port=5432 user=postgres password=P@ssword dbname=meloflow_db"
    volumes:
      - ./music_root:/app/music_root
